### ISSUE TITLE
Incompatibility with Node.js v22.x (Assertion failed in esm)

### ISSUE THREAD

**Issue by TomiyamaKensaku** [algolia/shipjs#1006]
Thank you for taking the time to look into this issue.

**Describe the bug**
When running shipjs prepare with Node.js v22.x, an assertion error occurs in the esm package, causing the process to fail. This issue does not occur when using Node.js v20.x

**To Reproduce**

Install Node.js v22.x (e.g., v22.11.0).
Run yarn install in a project that uses shipjs.
Execute yarn release:prepare.
Expected behavior
The shipjs prepare command should complete successfully, as it does in the Node.js v20.x environment, without any errors.

**Screenshots**
```
$ shipjs prepare

  #  /Users/******/.nvm/versions/node/v22.11.0/bin/node[69934]: void node::fs::InternalModuleStat(const FunctionCallbackInfo<v8::Value> &) at ../src/node_file.cc:1037
  #  Assertion failed: (args.Length()) >= (2)

----- JavaScript stack trace -----

1: /path/to/project/node_modules/esm/esm.js:1:34535
2: /path/to/project/node_modules/esm/esm.js:1:34176
3: /path/to/project/node_modules/esm/esm.js:1:34506
4: /path/to/project/node_modules/esm/esm.js:1:173374
5: /path/to/project/node_modules/esm/esm.js:1:173420
...
```
**Environment (please complete the following information):**
Node.js version: v22.11.0
Yarn version: v1.22.22
Ship.js version: v0.26.4

**Additional context**

This issue is likely caused by the dependency esm@3.2.25 used by shipjs, which might not fully support Node.js v22.x due to changes in its internal API.
Here is the result of yarn why esm:

```
=> Found "esm@3.2.25"
info Reasons this module exists
   - "shipjs" depends on it
   - Hoisted from "shipjs#esm"
```
This issue does not occur in Node.js v20.x (LTS: Iron). It would be greatly appreciated if compatibility with the latest Node.js v22.x (LTS: Jod) could be ensured.

**Comment by TomiyamaKensaku** [comment]
Thank you for taking the time to reply! I’d like to confirm if we’re aligned: should we either update the esm dependency to a newer version or remove it entirely if it’s deemed unnecessary? Let me know if there’s another approach you’d suggest.

**Comment by Haroenv** [comment]
Either option is fine, I guess we'll have to do a major version that changes which node versions are supported anyway?
