### ISSUE TITLE
Document configuration

### ISSUE THREAD

**Issue by KnisterPeter** [algolia/shipjs#326]
Thanks for this awesome project.
I have a project where there are multiple versions/releases to maintain, and I've seen the option to add a `shipjs.config.js` file and change the branch from `master` to something else.

Is this documented somewhere?

**Comment by eunjae-lee** [comment]
@KnisterPeter 
Hi there, is this what you need?
https://github.com/algolia/shipjs/blob/master/GUIDE.md#mergestrategy

Let me know if you want to do something else :)

**Comment by KnisterPeter** [comment]
Awesome. Thank you
