### ISSUE TITLE
Upload assets to GitHub release

### ISSUE THREAD

**Issue by uetchy** [algolia/shipjs#332]
**Is your feature request related to a problem? Please describe.**
As we can create a GitHub release now, it's at a good point to take the next step and let ship.js upload assets to a release at GitHub.

**Describe the solution you'd like**

#### 1. Define config something like this

```js
module.exports = {
  releases: {
    assetsToUpload: ["build/App.zip"]
  }
};
```

#### 3. Upload assets while creating a release

```
hub release create -a "<filepath>#<label>" <tag>
```

I'm ready for working this on.

**Comment by eunjae-lee** [comment]
Sounds good to me! :smile:
