### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by uetchy** [algolia/shipjs#333]
It's too early for having a logo?
I have some idea about it.

![Artboard](https://user-images.githubusercontent.com/431808/66739225-3c4cdf80-eeab-11e9-8557-9f1065cb53a3.png)

What do you think? @eunjae-lee

**Comment by eunjae-lee** [comment]
Hey, thanks for your great work 👍 
But I'm going to close this issue.
I'm totally bad at design but this time I kind of wanted to try it myself.
Sorry for that 😅

**Comment by uetchy** [comment]
@eunjae-lee I'm rooting for you! If there is anything I can help you with, don't hesitate to ask me about that ☺️

**Comment by eunjae-lee** [comment]
Thank you so much! 😄
