### ISSUE TITLE
support conventional-changelog-cli --config option

### ISSUE THREAD

**Issue by kazupon** [algolia/shipjs#375]
**Is your feature request related to a problem? Please describe.**
`convention-changelog-cli` can be specified user-defined conventions with `--config` option.

e.g. my convension: https://github.com/kazupon/git-commit-message-convention
```sh
# vue-i18n example: https://github.com/kazupon/vue-i18n/blob/dev/package.json#L101
$ conventional-changelog -i CHANGELOG.md -s -n ./node_modules/git-commit-message-convention/convention.js
```
And, to this option using, we can also define format of the generated CHANGELOG.

**Describe the solution you'd like**
```sh
NEW OPTION
	-c, --convention
	 A filepath of your convenion script
USAGE
	shipjs prepare --convention ./node_modules/git-commit-message-convention/convention.js
```

**Describe alternatives you've considered**
This new feature support that you can generate customized CHANGELOG with `--config` option of `conventional-changelog-cli`.

**Additional context**
CHANGELOG.md that generated with custom convention:
https://github.com/kazupon/vue-i18n/blob/dev/CHANGELOG.md

**Comment by kazupon** [comment]
Oh, I've noticed that it can be customized. :)
https://github.com/algolia/shipjs/blob/master/packages/shipjs-lib/src/lib/config/defaultConfig.js#L11

**Comment by eunjae-lee** [comment]
Hi @kazupon ,
Sorry for not having a proper documentation for configuration.
My next step is to improve it :) 
Let me know if you need anything else.

Thanks for your interest.
