### ISSUE TITLE
Replacing `hub`

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#401]
Should we replace `hub` with something else?
`hub` is not installed via npm.
It not natural that we have to install it separately.
_(Besides, the jobs on CircleCI are failing because for some reason they're failing to install `hub` on CircleCI)_

Initially it was to make it easy for me to ship Ship.js.
Should this be a legit alternative? https://github.com/octokit/rest.js

---

- [x] pull request: https://github.com/algolia/shipjs/pull/456
- [x] release: https://github.com/algolia/shipjs/pull/458
- [x] remove from doc: https://github.com/algolia/shipjs/pull/459

**Comment by jeetiss** [comment]
it will be nice

Maybe should create github bot for ship.js which will open PRs?

**Comment by uetchy** [comment]
I think we should eliminate as many as shell invocations that are basically externally dependent, and alien to the JavaScript ecosystem. `rest.js` is a great library to communicate with GitHub API and easy to integrate into ship.js.
