### ISSUE TITLE
First release flow

### ISSUE THREAD

**Issue by jeetiss** [algolia/shipjs#414]
**Is your feature request related to a problem? Please describe.**
When I added ship.js for new library that is never published, I got error message 
```
npm run release:prepare

> @jeetiss/try-shipjs@ release:prepare /Users/jeetiss/Projects/try-shipjs
> shipjs prepare

› Checking the current status.
Failed to prepare a release for the following reason(s).
  - There is no git tag for the current version (v0.0.0)
```

And I don't know how fix that

**Describe the solution you'd like**
We need describe first release flow better, and specify version that means unreleased package, like `0.0.0` or empty string.

**Describe alternatives you've considered**
Don't know

**Additional context**
Setup script that you added is so helpful ❤️
PS: I'm learning English now, fill free to edit my message for fixing some mistakes, and I hope that my message is understandable 🙏🏻

**Comment by Haroenv** [comment]
does this error happen on `npx shipjs setup`? Just clarifying

**Comment by jeetiss** [comment]
this error happen on `shipjs prepare`

You can see all attempts to fix this in my [try-shipjs](https://github.com/jeetiss/try-shipjs/commits/master) repo

**Comment by jeetiss** [comment]
I find `--first-release` flag in help, but it doesn't skip git tag validation

```
shipjs prepare --first-release
› Checking if `hub` exists.
› Checking the current status.
Failed to prepare a release for the following reason(s).
  - There is no git tag for the current version (v0.0.1)
```

**Comment by tyankatsu0105** [comment]
Hi! @jeetiss 👋
I had same issue before.

You need to release first version.

``<release-types>`` : ex) patch,minor,major
See [npm-version | npm Documentation](https://docs.npmjs.com/cli/version)
  
```bash
git checkout master
npm version <release-types>
git push origin master
git push --tags
```

And then, You can run `npm run release:prepare` after some commits.👍

**Comment by jeetiss** [comment]
Hi! @tyankatsu0105 🙌🏻

**Comment by eunjae-lee** [comment]
thinking of improving first-trying users' experience.
thanks for the doc which will save people in the meantime :)
