### ISSUE TITLE
go back to the previous branch after creating a PR

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#434]
After running `shipjs prepare`, user ends up on a branch like `releases/vx.y.z`.
What if we checkout the previous (base) branch after creating the PR?

Ship.js checking out to a release branch is not so much clear to users, so it might confuse them.

(a) Should we add more message to clarify it?
(b) or should we checkout the previous branch because there's no(or less) reason to stay on the release branch?

**Comment by uetchy** [comment]
users will probably want to edit CHANGELOG after that command.  So instead of switching branches, how about showing a list of tasks to be done or possible choices?

**Comment by eunjae-lee** [comment]
> showing a list of tasks to be done or possible choices?

Could you give me an example?

**Comment by Haroenv** [comment]
```
Release branch created, what do you want to do next?

❯◉ make changes to the changelog
 ◯ go back to the previous branch
```

**Comment by eunjae-lee** [comment]
Ah okay, got it.
I feel like we're giving too many choices to users if we do that.
I also don't want to make a sort of breaking change of switching branch which will confuse users.

One thing we can do is just print the current branch name right before `shipjs prepare` finishes. 

- If user runs `shipjs prepare` on their local machine, they will see the message and be aware.
- If user runs `shipjs prepare` on CI, they won't care anyway.

What do you think?

**Comment by uetchy** [comment]
Maybe something like that?

> You are currently on **releases/vX.X.X** branch, the purpose of which is to make changes to release materials including CHANGELOG.md to prepare for the next release.
> **PR url here**
> 
> Otherwise, you can safely check out another branch and get back to your development iteration.

**Comment by uetchy** [comment]
I'm working on this.
https://github.com/algolia/shipjs/blob/master/packages/shipjs/src/step/finished.js is a suitable place for this functionality.

**Comment by eunjae-lee** [comment]
@uetchy awesome!
We already know from which branch the user has started.
So can you also display an example command using the branch like:

```
git checkout master
```

**Comment by uetchy** [comment]
@eunjae-lee yeah that's a good idea to show command to checkout previous branch.
I created PR #554 for this issue.
