### ISSUE TITLE
shipjs prepare --manual

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#437]
The version is already 1.0.0-alpha.0
but user wants to release 1.0.0-alpha.0
and there is no tag.
what do we do?

This happens mostly when user tries to use Ship.js for the first time because the repository doesn't meet the convention which Ship.js assumes.

By adding `--manual`, `prepare` command will ask more questions to make things right even when it's out of convention.
After that, it will meet the convention, so no problem.

This feature will be documented as something like "Your first release with Ship.js"

**Comment by Haroenv** [comment]
what if the error which is thrown when we can't assume the convention would trigger these questions interactively instead?

**Comment by eunjae-lee** [comment]
It sounds much better than `--manual`.

- currentVersion and nextVersion are already being asked for correction.
- if a git tag for currentVersion is missing, then Ship.js has no idea from which commit it should generate changelog. This part can be solved by https://github.com/algolia/shipjs/issues/452 and https://github.com/algolia/shipjs/issues/453.

**Comment by eunjae-lee** [comment]
#452 #453 done
