### ISSUE TITLE
a new step before getNextVersion in prepare command

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#453]
We need to ask users if they want to release commits between `v${version}..HEAD`.
The current version might be wrong. It can be their first release at all and they put wrong (initially) version there of which git tag even doesn't exist yet.
For example, if the current version is `1.0.0`, then we could ask users if they want to release `v1.0.0..HEAD`.
If it's not, they can specify the range by using another tag, or a specific commit SHA.

Then with this range, later steps like `getNextVersion` and `updateChangelog` can get better results.

https://github.com/algolia/shipjs/blob/5fea13d17c24fffa2de326224a381f09ef80ca67/packages/shipjs-lib/src/lib/util/getNextVersion.js#L54

**Comment by eunjae-lee** [comment]
Should we have this all the time? or only when the conditions are met?

- currentVersion and nextVersion are the same (user probably overrode it).
or
- There is no tag for currentVersion.
or
- ...?

**Comment by uetchy** [comment]
> There is no tag for currentVersion.
This sounds good to me. With a newly created repo, I'm always compelled to manually tag the repo with `v0.0.0` or `v0.1.0` or whatever.
