### ISSUE TITLE
Add config for GitHub actions on "setup" stage

### ISSUE THREAD

**Issue by jeetiss** [algolia/shipjs#489]
I setup base GitHub actions config for shipjs trigger

Look 👉🏻https://github.com/jeetiss/try-shipjs/runs/330700313#step:6:59

Maybe we should add option to choose between CircleCI and GitHub Actions in setup step and then generate config for it? I can help with this.

What you think?

**Comment by uetchy** [comment]
It's nice if this shipped with `manual release` job:
https://github.com/algolia/shipjs/issues/346#issuecomment-546671789

**Comment by jeetiss** [comment]
@uetchy yee 🙌🏻

**Comment by eunjae-lee** [comment]
@jeetiss Sounds great.
I haven't used GitHub actions, so haven't put much effort there.
It'd be like to ask user to choose among CircleCI, GitHub actions, or nothing.
And https://github.com/algolia/shipjs/issues/346#issuecomment-546671789 can be definitely a part of questionnaires for GitHub actions.
@uetchy's dream will come true, thanks to @jeetiss :)

Let me know if you have any question or any help on this feature 😁
