### ISSUE TITLE
Do we need a chat room?

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#517]
Do we need a chat room such as spectrum or discord?

**Comment by uetchy** [comment]
Spectrum doesn’t offer iOS/Android app. So Discord or Slack would be a better option. I personally prefer Slack by the way.

**Comment by kazupon** [comment]
We should select chat accessible on mobile.
I personally prefer slack or discord.

**Comment by eunjae-lee** [comment]
I personally prefer Slack, too.
I wish it'd be public to anyone.
Is it possible to do it with Slack? Or should there be some sort of invitation system?
To be honest, I haven't been to slack communities much.
If anyone is aware of it, please let me know.
Otherwise, I will give it a little research.

**Comment by uetchy** [comment]
[Slackin](https://github.com/rauchg/slackin) is a great tool that makes a Slack team publically available. It offers an Invitation badge that can be embedded on README.

**Comment by eunjae-lee** [comment]
https://twitter.com/eunjae_lee/status/1206721573677350920
