### ISSUE TITLE
Upgrade Node.js v10

### ISSUE THREAD

**Issue by tyankatsu0105** [algolia/shipjs#544]
**Is your feature request related to a problem? Please describe.**
This is a proposal.

Ship.js Node.js version is 8.17.0 now.
However, LTS of Node.js v8 is 2019-12-31.
https://nodejs.org/en/about/releases/

It's time to upgrade to v10!

**Describe the solution you'd like**
Upgrade Node.js version

- `.node-version`
- `.nvmrc`

**Additional context**
I have a question.
Why is there `.node-version` and `.nvmrc`?
I wonder what it is for.

**Comment by eunjae-lee** [comment]
We should definitely think about moving to v10,
but I'm afraid there're still many apps/packages using v8 and
if we hurry, they won't be able to use this.

I still don't know when to move to v10. Any suggestion?

**Comment by tyankatsu0105** [comment]
Umm...
I have no idea.
I'm going to upgrade the repository's Node.js version that maintain by myself.
https://github.com/gridsome/eslint-plugin-gridsome/issues/49

But, TBH, I also don't know the good solution.😥

**Comment by eunjae-lee** [comment]
TBH, at work, I have bunch of stuff running on Node.js v8(which are going to use Ship.js).
Until they move onto v10, it's hard to do it here 😅 
I'm closing this, but we will surely move onto v10 when time comes!

**Comment by eunjae-lee** [comment]
We should do this when Ship.js goes `v1.0.0` because it's a breaking change.
At that time, we can merge this as well: https://github.com/algolia/shipjs/pull/591

**Comment by tyankatsu0105** [comment]
@eunjae-lee 
Maybe these help us to upgrade Node.js version!
- https://github.com/mysticatea/eslint-plugin-node/tree/master/docs/rules/no-unsupported-features
- https://github.com/cutenode/mingine

**Comment by eunjae-lee** [comment]
@tyankatsu0105 Thanks! I will take a look :)
