### ISSUE TITLE
Add \u002F insted of / ,when use `shipjs setup`

### ISSUE THREAD

**Issue by tyankatsu0105** [algolia/shipjs#548]
**Describe the bug**
Insert \u002F in ship.config.js

```js
module.exports = {
  publishCommand: ({ defaultCommand }) => `${defaultCommand} --access public`,
  mergeStrategy: { toReleaseBranch: { master: "releases" } },
  monorepo: {
    mainVersionFile: "lerna.json",
    packagesToBump: '["packages\u002F*"]',
    packagesToPublish: '["packages\u002F*"]'
  },
  buildCommand: () => null
};
```

**To Reproduce**
1. Set lerna.json
2. run `shipjs setup`
3. check ship.config.js

**Expected behavior**
Use `/` instead of `u002F`.

**Screenshots**

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: 12.13.0
 - `npm -v` or `yarn -v`: 
- Ship.js version: 0.12.0

**Additional context**
It may cause, here:
https://github.com/algolia/shipjs/blob/master/packages/shipjs/src/step/setup/addShipConfig.js#L54

https://www.npmjs.com/package/serialize-javascript#automatic-escaping-of-html-characters
>このパッケージの主な機能は、<script>要素のコンテンツとして追加することにより、HTMLドキュメントに埋め込むことができるリテラルJavaScriptの文字列にコードをシリアル化することです。

I think in this case,  don't need to use escape.

**Comment by eunjae-lee** [comment]
Thanks for the report :) 
Would you like to work on this?
As you know @uetchy already provided a way to fix this:
https://shipjs.slack.com/archives/CRTUJSCQ7/p1577101355020200
