### ISSUE TITLE
Claim js.org domain

### ISSUE THREAD

**Issue by uetchy** [algolia/shipjs#556]
Currently, ship.js website is hosted on Netlify (https://shipjs.netlify.com).
It's nice if we have a cool domain for our website, but it costs too much.
I think it's good timing to claim (almost) free [js.org](https://js.org) domain like `https://ship.js.org` (fortunately, ship.js.org is not yet occupied.)

doc: https://github.com/js-org/js.org/wiki

**Comment by eunjae-lee** [comment]
Okay it seems we need a github page.
I will see if it's possible without commiting `dist` folder.

**Comment by uetchy** [comment]
You are seeing a problem for committing `dist` to `gh-pages`? I think that's fine as long as it is separated from `master` branch.

**Comment by eunjae-lee** [comment]
Ah, will we use `gh-pages` branch just for GitHub Pages?
I haven't used it lately, so didn't know people use it that way.
It looks good!
I will work on it soon 😄

**Comment by uetchy** [comment]
Awesome! 

Here is todo list:

1. Publish GitHub Pages in `https://algoria.github.io/shipjs`, which is routed to `gh-pages` branch in `algoria/shipjs`.
1. Put `CNAME` file containing `ship.js.org` on `gh-pages`.
1. Create pull-request to make a change to [cnames_active.js](https://github.com/js-org/js.org/blob/master/cnames_active.js)
```
 "ship": "algoria.github.io/shipjs",
```

**Comment by eunjae-lee** [comment]
Thanks for the list!
Btw, it's "Algolia" 😆

**Comment by uetchy** [comment]
@eunjae-lee I seem to be unable to distinguish between "r" and "l" because I'm Japanese🙄😂

**Comment by uetchy** [comment]
Here is a reference branch
https://github.com/uetchy/shipjs/blob/gh-script/website/package.json

`npm run build && npm run deploy` will deploy `.vuepress/dist` to GitHub Pages.
