### ISSUE TITLE
slack messages

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#586]
We currently have:

- prepared
- releaseStart
- releaseSuccess

Do we really need "releaseStart"?
Is it useful in any way?

**Comment by jeetiss** [comment]
I think that "releaseStart" is excessive, maybe instead of this message add  "releaseFailed"  it will be helpful in rare cases: tests fails, etc.

**Comment by eunjae-lee** [comment]
Thanks for your opinion 🙂
