### ISSUE TITLE
Refine `releaseType`

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#594]
ref: https://github.com/algolia/shipjs/pull/441

We have `releaseType` variable exposed to hooks.
I thought its value could be `["major", "minor", "patch", "prerelease"]`.
Now that I revisit its implementation, it's based on `semver.diff`.
It's normally okay, but there's an odd.

* 1.2.3 -> 2.0.0: "major" ✅
* 1.2.3 -> 1.3.0: "minor" ✅
* 1.2.3 -> 1.2.4: "patch" ✅
* 1.2.3 -> 1.2.4-alpha.0: "prerelease" ✅
* 1.2.4-alpha.0 -> 1.2.4: "prerelease" ❌ (<- even don't know what to call this)

What kind of values do you think `releaseType` should have?

**Comment by kazupon** [comment]
We should organize the releases ways with state machine diagram once referring to the following information:

- semver: https://semver.org/
- stackoverflow: https://stackoverflow.com/questions/28421489/what-is-the-convention-for-versioning-npm-packages-prior-to-1-0-0
- npm docs: https://docs.npmjs.com/cli/version

As a result of this, I think that it will be the hint to determine the specification. 😉

**Comment by eunjae-lee** [comment]
Thanks for the links!

I've got an idea.

* 1.2.4-alpha.0 -> 1.2.4

What if we call it a `patch` ?

It's because, ... it was `1.2.4-alpha.0` and not it's `1.2.4`.
It means it used to be something else before `-alpha.0`, most likely `1.2.3` (we cannot be sure, though).

So, 

> `versionA -> verisonB`

when versionA is a prerelease type (meaning, it has tags like alpha, beta, rc, etc), and versionB is not a prerelease type, we can infer the releaseType.

* When versionB is 1.2.4, it's `patch`.
* When versionB is 1.3.0, it's `minor`. (last digit is 0)
* When versionB is 2.0.0, it's `major`. (the middle digit is 0)

So we end up having only `major, minor, patch, prerelease` as releaseType.

What do you think?
