### ISSUE TITLE
Provide a way to filter out unnecessary preparation

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#645]
We could provide a way so that scheduled `shipjs prepare` won't create unnecessary PRs with meaningless commits.

ref: https://github.com/algolia/shipjs/pull/644

**Comment by jeetiss** [comment]
I think that will be better this flow:

- shipjs detect that release branch doesn't have commits for release
- shipjs asks about continue release anyway and in CI mode with `--yes` flag skip that release

With that behaviour doesn't need new config props, and shipjs have a way to release version without changes.

**Comment by eunjae-lee** [comment]
The issue I had with #644 was, as you know `shipjs prepare --yes` is scheduled on CircleCI.
The latest PR contained only `chore(deps)` commits.
Some people may want to release it, and people don't.

If people still want to schedule it with `--yes`, then we need to provide a way for people to configure what to release and what not.

**Comment by jeetiss** [comment]
I understand you point.

I had this issues too in https://github.com/uploadcare/uploadcare-upload-client/pull/183 and https://github.com/uploadcare/uploadcare-upload-client/pull/176

What is use case for release library with only `chore` commits, if you wanna release those, name it `fix` or else?

**Comment by Haroenv** [comment]
```
shouldCreateRelease({commits, changelog, version, gitDiffToPreviousVersion, ...otherInfo}) {
// default: true
// check if changelog has contents, if not, false
// or do something with the commits yourself
// maybe the git diff between the previous version?
}
```

Something like that could make sense?

**Comment by eunjae-lee** [comment]
> What is use case for release library with only `chore` commits
@jeetiss I have no idea. It's totally up to users. Unlike you didn't want to release uploadcare/uploadcare-upload-client#183 and uploadcare/uploadcare-upload-client#176, some user might want to release whatever it is (maybe want to keep up to date with all the dependencies? IDK).

So it'd be nice to give a way to users so that they can decide.

---

> ```
> shouldCreateRelease({commits, changelog, version, gitDiffToPreviousVersion, ...otherInfo}) {
> // default: true
> // check if changelog has contents, if not, false
> // or do something with the commits yourself
> // maybe the git diff between the previous version?
> }
> ```
> 
> Something like that could make sense?

@Haroenv Yeah that makes sense. We can provide a bunch of information so that user can do whatever they want to do.

**Comment by eunjae-lee** [comment]
Since we have `shouldRelease` hook (which is not publicly documented, though), I guess `shouldPrepare` could make sense.

```js
shouldPrepare({ commits, changelog, version, releaseType, releaseTag, commitNumbersPerType }) {
  /*
    commits: array of strings. `git log --pretty=format:%s` should be fine for this. (only titles)
    changelog: string. only the current version part.
    version: string.
    releaseType: 'major' | 'minor' | 'patch' | 'prerelease'
    releaseTag: 'latest' | 'alpha' | 'beta' | 'rc' | ... (whatever)
    commitNumbersPerType: { [type]: number } , for example, { 'feat': 10, 'chore': 3, fix: 4 } 
  */
}
```

In case of `git diff`, I can't think of any example using it. It might be too difficult to handle programmatically...? We can add it any time.

What do you think?

**Comment by jeetiss** [comment]
@eunjae-lee I have waited this stuff, thanks ❤️

**Comment by eunjae-lee** [comment]
@jeetiss Let me know if you have any feedback while using it 🙂
