### ISSUE TITLE
Refine publish commands on PR

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#660]
![image](https://user-images.githubusercontent.com/499898/74032454-480d6600-49b4-11ea-92ec-51bd2f7bce48.png)

Need to drop the path before the working directory.

**Comment by Haroenv** [comment]
seems like https://github.com/algolia/shipjs/blob/166626d2ee8c66170943f99c9212ae486bae45f0/packages/shipjs-lib/src/lib/config/defaultConfig.js#L63 is the bit which is wrong

**Comment by eunjae-lee** [comment]
Yeah, thanks! I'll look into it :)
