### ISSUE TITLE
See if it works with Netlify without circle ci

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#674]

**Comment by Haroenv** [comment]
Do you mean publishing on npm via Netlify? Since you can provide environment variables, I don't see why it wouldn't work.

**Comment by eunjae-lee** [comment]
Yes, I was thinking the same thing. I will give it a test and if it works as expected, I might add Netlify config as an option at `shipjs setup` command.

**Comment by eunjae-lee** [comment]
Stumbled upon an ssl issue. `shipjs trigger` command needs to be able to push stuff to origin.

```
    Host key verification failed.

    fatal: Could not read from remote repository.
```

I'll try this later.
