### ISSUE TITLE
Does the project take @shipjs GitHub Account?

### ISSUE THREAD

**Issue by azu** [algolia/shipjs#684]
**Is your feature request related to a problem? Please describe.**
It is not a feature request. It is just suggestion.

Shipjs setup `shipjs-manual-prepare.yml` on GitHub Action.

This script use `@shipjs prepare` comment as command by default.
But, https://github.com/shipjs account does not exists.
So, This comment has not been syntax highlighted and its look like strange comment.

![image](https://user-images.githubusercontent.com/19714/75627644-58141080-5c15-11ea-9847-7d5e5d21f1e4.png)

**Describe the solution you'd like**
Take @shipjs account as placeholder

FYI: You can convert account to organization later 
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/converting-a-user-into-an-organization

**Describe alternatives you've considered**
Use non `@` comment like `shipjs prepare`  or `/shipjs prepare`

https://bors.tech/ use this approach, but they also have https://github.com/bors
Example `bors +r`

**Additional context**
Potentially, attacker can take @shipjs account and use it as fishing.

**Comment by Haroenv** [comment]
Good call! I've got the organisation as a placeholder for now.

**Comment by azu** [comment]
Nice! My concern is resolved.
