### ISSUE TITLE
pathspec 'develop' did not match any file(s) known to git

### ISSUE THREAD

**Issue by tyankatsu0105** [algolia/shipjs#777]
**Describe the bug**

I use `shipjs trigger` with github actions.
But actions can't checkout baseBranch `develop`.
Error log is [here](https://github.com/gridsome/eslint-plugin-gridsome/runs/617765300?check_suite_focus=true).

base branch => develop
release branch => master

**To Reproduce**
1. Run `npm run release:prepare` on develop.
2. merge PR.
3. There is error...

**Expected behavior**
Pass shipjs trigger

**Screenshots**

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: 12.x
 - `npm -v` or `yarn -v`: 
- Ship.js version: 0.18.2

**Additional context**
It might be caused by actions/checkout@v2😭

**Comment by tyankatsu0105** [comment]
Um... It's interesting to me.

**Comment by tyankatsu0105** [comment]
npm release is succeeds.
But `git checkout develop` is failed.

**Comment by tyankatsu0105** [comment]
I added this before npm run release:trigger:
```yml
- run: git fetch
```

Then, the error is change.
```bash
$ git checkout develop
Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
$ git merge master
fatal: refusing to merge unrelated histories
```

**Comment by tyankatsu0105** [comment]
@eunjae-lee 
Can we need `git merge` option `--allow-unrelated-histories`?
https://github.com/algolia/shipjs/blob/master/packages/shipjs/src/step/release/gitPush.js#L21

**Comment by jeetiss** [comment]
Hello @tyankatsu0105
I think that `fetch-depth: 0` parameter for [actions/checkout](https://github.com/actions/checkout#usage) should help you!

**Comment by tyankatsu0105** [comment]
`0 indicates all history.`
Umm.. I see.
I'll try!!

**Comment by tyankatsu0105** [comment]
@jeetiss OMG You are right!!
It's succeeds!!
Thanks!!
https://github.com/gridsome/eslint-plugin-gridsome/runs/618888461?check_suite_focus=true
