### ISSUE TITLE
How about Ship.js badge?

### ISSUE THREAD

**Issue by tyankatsu0105** [algolia/shipjs#783]
**Is your feature request related to a problem? Please describe.**
How about adding a badge to the README for a project that uses Ship.js?
Like this:
<img width="902" alt="スクリーンショット 2020-04-29 11 17 09" src="https://user-images.githubusercontent.com/28397593/80555379-16cc9100-8a0b-11ea-829b-4fbb293b4362.png">

**Describe the solution you'd like**
Add these code:
```
<a title="deploy" href="https://github.com/algolia/shipjs" rel="nofollow">
  <img src="https://img.shields.io/badge/deploy-🛳Ship.js-blue?style=flat">
</a>
```
or
```
[![deploy](https://img.shields.io/badge/deploy-🛳Ship.js-blue?style=flat)](https://github.com/algolia/shipjs)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by eunjae-lee** [comment]
It's a cool idea!
But it will be difficult for us to find exactly where to inject that snippet inside README.me, and user might not want it.
What do you think of documenting that snippet in the 'getting started' page?

**Comment by tyankatsu0105** [comment]
>What do you think of documenting that snippet in the 'getting started' page?

I"m just thinking of that too!
I will send PR🙂
