### ISSUE TITLE
Protected branch update failed for xxx

### ISSUE THREAD

**Issue by tyankatsu0105** [algolia/shipjs#805]
**Describe the bug**
re #786

In toReleaseBranch strategy, development branch has been protected.
That's why, `git push origin-with-token develop` is failed.

See: https://github.com/gridsome/eslint-plugin-gridsome/runs/656381715?check_suite_focus=true

**To Reproduce**

1. In develop branch
2. create topic branch from develop branch
3. merge topic branch to develop branch
4. checkout develop branch
5. git pull origin develop
6. run `shipjs prepare`
7. merge release branch to master branch
8. GitHub Actions is failed

**Expected behavior**
I think, we need `-f` or `-force` option.
`git push -f origin-with-token develop`

**Environment (please complete the following information):**

- environment: (your local machine, CircleCI, Travis CI, etc.) GitHub Actions
- `node -v`: 13.2.0
- `npm -v` or `yarn -v`: 6.13.1
- Ship.js version: 0.18.4

**Comment by eunjae-lee** [comment]
Sorry for the trouble. This is a bummer 🤦🏻‍♂️

If I understand correctly, `git push -f` won't work for protected branch, because it's what it's expected.

I'll see what we can do about this.
If anyone has an idea, please feel free to leave here.

**Comment by tyankatsu0105** [comment]
@eunjae-lee 
According to [this posts](https://help.github.com/en/github/administering-a-repository/enabling-force-pushes-to-a-protected-branch), developer can use force push to protected branch if update branch settings.

But, I think this way is not good...
I don't want to use force option...
It's scaring...

**Comment by eunjae-lee** [comment]
Ahh okay, if it's enabled, then you can force-push to a protected branch.
As far as I understand, this `force-push` won't mess up the commit history, unlike force-pushing after rebase.
But before we decide to provide an option for force-push, let's dig more.
