### ISSUE TITLE
Updating guide on `release:prepare` and `release:trigger`

### ISSUE THREAD

**Issue by eunjae-lee** [algolia/shipjs#823]
We normally don't run `release:trigger` manually.
What if we get rid of it?

Instead, we can guide them to add `"release": "shipjs prepare"` in their package.json.
And for the CI services, they can trigger like the following:

```
yarn shipjs trigger
# or
npx shipjs trigger
```

**Comment by tyankatsu0105** [comment]
>We normally don't run release:trigger manually.

I guess so. I have never used trigger command on the local machine😂

>"release": "shipjs prepare" in their package.json.

I think people will be confused when seeing `"release": "shipjs prepare"`.
Because `shipjs prepare` commands can prepare commit and create PR, but can't release.

**Comment by eunjae-lee** [comment]
I can't think of any better name 😂
I'll leave it as is until I actually get to work on this.

**Comment by Haroenv** [comment]
I like `release` as the command, since that's what I'd use intuitively

**Comment by tyankatsu0105** [comment]
Umm...
I can't think too.
How about `"prepare": "shipjs prepare"`?

**Comment by eunjae-lee** [comment]
"yarn run prepare" doesn't feel like I'm using a release tool.

Anyway this is not a big change but mostly the doc and some snippets in `setup` flow. So I'll continue with `release` for now.
