### ISSUE TITLE
[Vulnerability] An issue with shelljs in `shipjs-lib` internal package

### ISSUE THREAD

**Issue by vinayakkulkarni** [algolia/shipjs#968]
**Describe the bug**
Not necessarily a bug, but an issue with one of the dependencies – `shelljs`

**To Reproduce**
`npm i shipjs` throws an vulnerability 

**Expected behavior**
npm audit to show 0 vulnerabilities found.

**Screenshots**
<img width="656" alt="Screenshot 2022-01-31 at 2 12 17 AM" src="https://user-images.githubusercontent.com/19776877/151717071-7e99cfb6-d97e-4365-963a-defb953ca9f4.png">

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: v17.3.1
 - `npm -v`: 8.3.0
- Ship.js version: ^0.24.1

**Additional context**
Gotta bump up shelljs here – https://github.com/algolia/shipjs/blob/main/packages/shipjs-lib/package.json#L52

**Comment by Haroenv** [comment]
Thanks for opening the issue. Are you willing to make a PR which updates that dependency?

**Comment by vinayakkulkarni** [comment]
> Thanks for opening the issue. Are you willing to make a PR which updates that dependency?

Done #969

**Comment by eunjae-lee** [comment]
Thanks for your contribution! Feel free to open a PR to include yourself as contributor :)

```
yarn contributors:add vinayakkulkarni code
```
