### ISSUE TITLE
Setup wizard showing incomplete branch names

### ISSUE THREAD

**Issue by SevenOutman** [algolia/shipjs#972]
**Describe the bug**
After run `npx shipjs setup`, the "What is your base branch?" prompt appears but the options to select are displaying branch names not complete, but seeming to be trimmed of several leading letters.

**To Reproduce**
1. Run `npx shipjs setup`

**Expected behavior**
Showing complete branch names

**Screenshots**
<img width="493" alt="image" src="https://user-images.githubusercontent.com/8225666/153350141-82a613f1-14af-4f8c-8f2a-dbb052621d16.png">

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: v14.18.1
 - `npm -v` or `yarn -v`: npm 6.14.15
- Ship.js version: 0.24.2 (via npx)

**Additional context:**
I have multiple origins configured. Looks like it's the possible cause.
https://github.com/algolia/shipjs/blob/main/packages/shipjs-lib/src/lib/git/getRemoteBranches.js#L14

**Comment by eunjae-lee** [comment]
Hi @SevenOutman, thanks for reporting your issue.
Your guess is probably right. If you don't mind, can you share the output of `git remote` and `git branch -r` (probably just a part of them)?

**Comment by SevenOutman** [comment]
Sure. They are pasted below
<img width="233" alt="image" src="https://user-images.githubusercontent.com/8225666/153545785-a153e085-caae-48aa-9b96-9f378016a85d.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/8225666/153545817-87429856-91e9-4d51-a6f3-4d85798bfc3b.png">

**Comment by eunjae-lee** [comment]
Thanks for providing the info. Yeah that function needs to change to cover all the origins. Are you interested in contributing? If not, it's okay. I can work on this next week if it's okay with you.

**Comment by SevenOutman** [comment]
I'm glad to help but I happen to be having a whole week off next week 😹.

**Comment by eunjae-lee** [comment]
Fixed in `v0.24.3` :)
