### ISSUE TITLE
"Git tag doesn't exist" in GitHub Actions

### ISSUE THREAD

**Issue by SevenOutman** [algolia/shipjs#973]
**Describe the bug**
Hi, I was trying to setup shipjs with my GitHub Actions workflow and got this error when doing a `shipjs prepare --dry-run`. I checked the repo and was sure that the tag exists. No clue what went wrong.

**Expected behavior**
`shipjs prepare` works as expected

**Screenshots**
https://github.com/rsuite/rsuite/runs/5138487184?check_suite_focus=true
<img width="691" alt="image" src="https://user-images.githubusercontent.com/8225666/153383430-1d946c4e-590b-44fd-ae1d-9687cc3606c5.png">

**Comment by eunjae-lee** [comment]
Hi @SevenOutman I think on GH Action, tags are not fetched properly.
Reading [this issue](https://github.com/actions/checkout/issues/100), I'd suggest you to try 

```diff
    steps:
       - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
```

**Comment by SevenOutman** [comment]
> Hi @SevenOutman I think on GH Action, tags are not fetched properly. Reading [this issue](https://github.com/actions/checkout/issues/100), I'd suggest you to try
> 
> ```diff
>     steps:
>        - uses: actions/checkout@v2
> +        with:
> +          fetch-depth: 0
> ```

It works, thanks!
