### ISSUE TITLE
fix(deps): issue with one of the transitive dependency causing dependabot alert(s)

### ISSUE THREAD

**Issue by vinayakkulkarni** [algolia/shipjs#980]
**Describe the bug**
This isn't a bug per se but an issue with one of the dependencies which causes all my repos with a Dependabot Alert portrayed in the screenshot below

**To Reproduce**
3. npm i -D shipjs

**Expected behavior**
No CVE error(s)

**Screenshots**
![Screenshot 2022-04-25 at 10 11 14 AM](https://user-images.githubusercontent.com/19776877/165022080-0e1ca303-9090-4b87-90db-a397a83ad007.png)

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: v18.0.0
 - `npm -v`: v8.6.0
- Ship.js version: v0.24.4

**Additional context**
Example alert – https://github.com/vinayakkulkarni/mapbox-gl-interpolate-heatmap/security/dependabot/8

**Comment by Haroenv** [comment]
Are you interested in making a pull request? Based on the error message you get I'm not sure which one requires async, it's likely deeply transitive. The dependencies are:

https://github.com/algolia/shipjs/blob/4ce9a314fdb79cc33bd519ee23ed3f8c0971cf26/packages/shipjs-lib/package.json#L47-L53

and 

https://github.com/algolia/shipjs/blob/4ce9a314fdb79cc33bd519ee23ed3f8c0971cf26/packages/shipjs/package.json#L34-L60
